### ISSUE TITLE
Trouble using LpSolve in java

### ISSUE THREAD

**Issue by akanshatamu** [DuncanvR/2dcuttingstock#1]
Hii,

I am getting the following error when I run LpSolve using java,

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Program Files\Java\jdk1.7.0_51\jre\bin\lpsolve55j.dll: Can't find dependent libraries

Do you have any clue why i get this error?

Thanks,

**Comment by DuncanvR** [comment]
The error is fairly descriptive; the program can't find `lpsolve55j.dll`. Did you place it in the `lib/` folder, like the readme states?
You'll have to provide more details about the steps you've taken --- which files did you place where, what commands did you execute? --- before I can give a more meaningful response. Either way I don't have a Windows machine, so I won't be able to reproduce them.

**Comment by akanshatamu** [comment]
Thanks for the reply.

I am now able to run the files. I had misplaced the dll files.
 In addition, I see some necessity of 2d cutting stock in commercial
purposes, like infrastructure industry for cutting sheets and glasses.
Are you interested in a collaboration for building on this idea and making
it commercial.

I would like to have you write me from a non github email if possible.

Thanks

**Comment by DuncanvR** [comment]
Good! Nice to hear it still runs; I actually never use it myself.

Please note that this wasn't designed for professional use, merely for some quick calculations around the house. As noted in the readme, the implementation of the pricing problem is fairly naive, meaning that the running time will explode when given larger instances. It could definitely be improved --- just thinking about it now I'm coming up all sorts of ideas --- but I don't have the time to do that and I don't see that changing any time soon.

If you'd like, I could ask some friends of mine who do software development for a living if they're interested in supporting this. But they'll probably need some more info about you're envisioned use cases and business plan.

**Comment by akanshatamu** [comment]
Dear Duncan,

True, the code exploded when increased the problem size.

I would appreciate if you please give me links of your friends who are
available to build on this code.

My email address is akansha.tamu@gmail.com

I can talk to them directly about the requirements and other formalities.

Thanks

**Comment by DuncanvR** [comment]
I'll let them know, and ask them to comment here if they're interested. That might very well mean this stays quiet, of course.
Either way I'll close this, as the issue itself has been resolved.
